# Generated by Django 4.1.1 on 2022-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteiner',
            name='tipo_conteiner',
            field=models.IntegerField(),
        ),
    ]
